config/routes.rb
Rails.application.routes.draw do
  resources :cocktails,  only: [ :index, :show, :new, :create ] do
    resources :doses, only: [ :new, :create ]
  end
  resources :doses, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
    has_many :doses, dependent: :destroy
    has_many :ingredients, through: :doses
    has_one_attached :photo

    validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, presence: true
  validates :ingredient, presence: true
  validates_uniqueness_of :cocktail, :scope => :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :doses
    has_many :cocktails, through: :doses

    validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [ :show ]
  def index
    @cocktails = Cocktail.all
  end

  def show
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
    @dose = Dose.new
    @cocktails = Cocktail.all
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end 
  end  

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end  

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
   # @ingredients = Ingredient.all
  end   
  
    def create
      @cocktail = Cocktail.find(params[:cocktail_id])
      @dose = Dose.new(dose_params)
      @dose.cocktail = @cocktail
      if @dose.save
        redirect_to cocktail_path(@cocktail)
      else
        @review = Review.new
        render "cocktails/show"
      end
    end
  
    def destroy
      @dose = Dose.find(params[:id])
      @dose.destroy
      redirect_to cocktail_path(@dose.cocktail)
    end
  
    private
  
    def dose_params
      params.require(:dose).permit(:description, :ingredient_id)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/cocktails/index.html.erb
<div class="header-index">
  <h2>We care about your drink</h2>
  <h4>Read our recipes, shake, enjoy 🍸</h4>
</div>
<div class="container">
  <h2>Our cocktails:</h2>
  <% @cocktails.each do |cocktail| %>
    <div class="cocktail-card">
      <div class="card-text"> 
        <%= link_to cocktail.name, cocktail_path(cocktail), {:style=>'text-align: center;', :class => "css_class"}%>
        <% if cocktail.photo.attached? %>
          <div class="card-category"> <%= cl_image_tag cocktail.photo.key, width: 400, height: 300, crop: :fill %></div>
       <% else %>
          <div class="card-category"> <img src="https://previews.123rf.com/images/dbelashova/dbelashova1609/dbelashova160900189/62815611-cocktail-icon-outline-vector-contour-isolated-on-white-background.jpg" width="400" height="300"></div>
       <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/cocktails/new.html.erb
<div class="form-container">
  <div class="form-new">
    <%= simple_form_for [ @cocktail ] do |f| %>
    <%= f.input :name, class: 'name-bar-form' %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Add cocktail", class: "btn btn-primary" %>
  <% end %>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container-doses">
  <h1><%= @cocktail.name %></h1>
  <% @cocktail.doses.each do |dose| %>
    <div class="show-ingredients"> 
      <h3>Ingredient: <%= dose.ingredient.name %></h3>
      <h3>Dose: <%= dose.description %></h3>
      <%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
        <i class="fa fa-trash destroy_dose"></i>
      <% end %>
  <% end %>
      <%= link_to new_cocktail_dose_path(@cocktail, @ingredient) do %>
        <i class="fas fa-plus"></i>
    </div>
  <% end %>
</div>  
  <div class="pic-container">
    <% if @cocktail.photo.attached? %>
      <%= cl_image_tag @cocktail.photo.key, height: 300, crop: :fill %>
    <% else %>
      <div class="card-category">
      <img src="https://previews.123rf.com/images/polyudova/polyudova1704/polyudova170400064/77028714-alcoholic-cocktail-hand-drawn-vector-illustration-vintage-cocktail-icon-with-ice-and-leaves-of-mint-.jpg" alt="default cocktail pic" width="300" height="300" >
      </div>
  <% end %>
  </div>

app/views/doses/new.html.erb
<h3>Add a new dose</h3>
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.association :ingredient, collection: Ingredient.order(:name), prompt: "Choose your ingredient" %>
  <%= f.input :description %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to cocktails_path, class: "navbar-brand" do %>
    Home
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Create a cocktail", new_cocktail_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</div>
    <%= yield %>
  </body>
</html>